camp = {
	['path'] = 'Mods/aircraft/F-5E/Missions/EN/Campaigns/Desert Tiger 76/',
	['date'] = {
		['year'] = 1976,
		['day'] = 6,
		['month'] = 4,
	},
	['idle_time_min'] = 10800,
	['freq_max'] = 399,
	['dawn'] = 18900,
	['idle_time_max'] = 43200,
	['time'] = 50134,
	['startup_time_player'] = 600,
	['weather'] = {
		['zoneNextTemp'] = 39,
		['pHigh'] = 100,
		['pLow'] = 0,
		['zoneNext'] = 'high',
		['zoneTemp'] = 43,
		['refTemp'] = 38,
		['zoneEnd'] = 238937,
		['zoneStart'] = -1,
		['zone'] = 'high',
	},
	['dusk'] = 65700,
	['freq_min'] = 225,
	['debug'] = false,
	['hotstart'] = false,
	['flag'] = {
	},
	['units'] = 'imperial',
	['startup_time_ai'] = 180,
	['player'] = {
		['pack'] = {
			['Flare Illumination'] = {
			},
			['main'] = {
				[1] = {
					['number'] = 2,
					['tot_to'] = 10800,
					['skill'] = 'High',
					['firepower'] = 20,
					['livery'] = {
						[1] = 'aggressor `snake` scheme',
						[2] = 'aggressor `desert` scheme',
						[3] = 'US USAF Grape 31',
					},
					['base'] = 'Nellis AFB',
					['playable'] = true,
					['type'] = 'F-5E-3',
					['route'] = {
						[1] = {
							['alt'] = 0,
							['x'] = -397971,
							['id'] = 'Taxi',
							['eta'] = 0,
							['y'] = -17639.5,
						},
						[2] = {
							['alt'] = 1563,
							['x'] = -397971,
							['id'] = 'Departure',
							['eta'] = 620,
							['y'] = -17639.5,
						},
						[3] = {
							['alt'] = 4876.8,
							['x'] = -382209.49576773,
							['id'] = 'Join',
							['eta'] = 806.54270270271,
							['y'] = -43396.239620847,
						},
						[4] = {
							['alt'] = 4876.8,
							['x'] = -374232.87079104,
							['id'] = 'Nav',
							['eta'] = 877.34723187402,
							['y'] = -56431.280537626,
						},
						[5] = {
							['alt'] = 4572,
							['x'] = -372641.92793986,
							['id'] = 'IP',
							['eta'] = 891.46923959603,
							['y'] = -59031.127618567,
						},
						[6] = {
							['alt'] = 4572,
							['x'] = -363951.24602642,
							['id'] = 'Attack',
							['eta'] = 951.46923959603,
							['y'] = -73233.048188667,
						},
						[7] = {
							['alt'] = 4572,
							['x'] = -357943.71428572,
							['id'] = 'Target',
							['eta'] = 992.94491527171,
							['y'] = -83050.285714287,
						},
						[8] = {
							['alt'] = 4572,
							['x'] = -326823.59590495,
							['id'] = 'Egress',
							['eta'] = 1124.4205909474,
							['y'] = -64006.731103427,
						},
						[9] = {
							['alt'] = 4876.8,
							['x'] = -329377.17891137,
							['id'] = 'Nav',
							['eta'] = 1138.5425986694,
							['y'] = -62342.544266163,
						},
						[10] = {
							['alt'] = 4876.8,
							['x'] = -372672.59953685,
							['id'] = 'Split',
							['eta'] = 1377.9780361952,
							['y'] = -34126.633940328,
						},
						[11] = {
							['alt'] = 4876.8,
							['x'] = -397971,
							['id'] = 'Land',
							['eta'] = 1517.8850632222,
							['y'] = -17639.5,
						},
					},
					['country'] = 'USA',
					['airdromeId'] = 4,
					['callsign'] = 'Enfield81',
					['loadout'] = {
						['self_escort'] = false,
						['night'] = false,
						['capability'] = 5,
						['expend'] = 'All',
						['hAttack'] = 4572,
						['attributes'] = {
							[1] = 'soft',
							[2] = 'hard',
							[3] = 'armor',
							[4] = 'SA-6',
							[5] = 'SR',
						},
						['vCruise'] = 215.83333333333,
						['stores'] = {
							['pylons'] = {
								[1] = {
									['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
								},
								[7] = {
									['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
								},
								[4] = {
									['CLSID'] = '{MER-5E_MK82x5}',
								},
							},
							['fuel'] = 2046,
							['flare'] = 15,
							['ammo_type'] = 1,
							['chaff'] = 30,
							['gun'] = 100,
						},
						['LDSD'] = false,
						['support'] = {
							['Escort'] = true,
							['SEAD'] = true,
						},
						['adverseWeather'] = false,
						['day'] = true,
						['hCruise'] = 4876.8,
						['name'] = 'SR, Mk-82*5, AIM-9P*2',
						['vAttack'] = 277.5,
						['range'] = 130000,
						['firepower'] = 10,
						['weaponType'] = 'Bombs',
						['sortie_rate'] = 2,
					},
					['eta_offset'] = 0,
					['player'] = true,
					['name'] = '64 FWS',
					['tot_from'] = 0,
					['target_name'] = '102 EWR Site',
					['target'] = {
						['elements'] = {
							[1] = {
								['name'] = '102 Radar',
							},
							[2] = {
								['name'] = '102 Command Post',
							},
						},
						['groupId'] = 60,
						['class'] = 'vehicle',
						['firepower'] = {
							['min'] = 20,
							['max'] = 40,
						},
						['y'] = -83050.285714287,
						['x'] = -357943.71428572,
						['name'] = '102 EWR Site',
						['dead_last'] = 0,
						['alive'] = 100,
						['priority'] = 3,
						['task'] = 'Strike',
						['attributes'] = {
							[1] = 'soft',
							[2] = 'SR',
						},
					},
					['task'] = 'Strike',
					['frequency'] = 232.6,
				},
			},
			['Laser Illumination'] = {
			},
			['SEAD'] = {
			},
			['Escort Jammer'] = {
			},
			['Escort'] = {
			},
		},
		['side'] = 'blue',
		['group'] = {
			['uncontrolled'] = false,
			['taskSelected'] = true,
			['modulation'] = 0,
			['groupId'] = 100013,
			['tasks'] = {
			},
			['route'] = {
				['points'] = {
					[1] = {
						['alt'] = 1663,
						['briefing_name'] = 'Departure',
						['action'] = 'From Parking Area',
						['alt_type'] = 'BARO',
						['airdromeId'] = 4,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 0,
						['y'] = -17639.5,
						['formation_template'] = '',
						['name'] = 'Departure',
						['ETA_locked'] = true,
						['speed'] = 161.875,
						['x'] = -397971,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 393217,
													['name'] = 5,
													['formationIndex'] = 6,
												},
											},
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'ControlledTask',
										['number'] = 2,
										['params'] = {
											['task'] = {
												['id'] = 'Orbit',
												['params'] = {
													['altitude'] = 1663,
													['pattern'] = 'Circle',
													['speed'] = 143.88888888889,
												},
											},
											['stopCondition'] = {
												['time'] = 620,
											},
										},
									},
									[3] = {
										['number'] = 3,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = 2,
													['name'] = 1,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'TakeOffParking',
					},
					[2] = {
						['alt'] = 4876.8,
						['briefing_name'] = 'Join',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 806.54270270271,
						['y'] = -43396.239620847,
						['formation_template'] = '',
						['name'] = 'Join: 287/17NM',
						['ETA_locked'] = false,
						['speed'] = 37.439555151651,
						['x'] = -382209.49576773,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 458753,
													['name'] = 5,
													['formationIndex'] = 7,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[3] = {
						['alt'] = 4876.8,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 877.34723187402,
						['y'] = -56431.280537626,
						['formation_template'] = '',
						['name'] = 'Nav: 287/9NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['x'] = -374232.87079104,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[4] = {
						['alt'] = 4572,
						['briefing_name'] = 'IP',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 891.46923959603,
						['y'] = -59031.127618567,
						['formation_template'] = '',
						['name'] = 'IP: 287/2NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['x'] = -372641.92793986,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'AttackGroup',
										['number'] = 1,
										['params'] = {
											['expend'] = 'All',
											['weaponType'] = 2032,
											['groupId'] = 60,
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[5] = {
						['alt'] = 4572,
						['briefing_name'] = 'Target',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 992.94491527171,
						['y'] = -83050.285714287,
						['formation_template'] = '',
						['name'] = 'Target: 287/16NM',
						['ETA_locked'] = true,
						['speed'] = 277.5,
						['x'] = -357943.71428572,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[6] = {
						['alt'] = 4572,
						['briefing_name'] = 'Egress',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1124.4205909474,
						['y'] = -64006.731103427,
						['formation_template'] = '',
						['name'] = 'Egress: 017/20NM',
						['ETA_locked'] = false,
						['speed'] = 277.5,
						['x'] = -326823.59590495,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[7] = {
						['alt'] = 4876.8,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1138.5425986694,
						['y'] = -62342.544266163,
						['formation_template'] = '',
						['name'] = 'Nav: 132/2NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['x'] = -329377.17891137,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[8] = {
						['alt'] = 4876.8,
						['briefing_name'] = 'Split',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1377.9780361952,
						['y'] = -34126.633940328,
						['formation_template'] = '',
						['name'] = 'Split: 132/28NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['x'] = -372672.59953685,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 393217,
													['name'] = 5,
													['formationIndex'] = 6,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[9] = {
						['alt'] = 4876.8,
						['briefing_name'] = 'Land',
						['action'] = 'Landing',
						['alt_type'] = 'BARO',
						['airdromeId'] = 4,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1517.8850632222,
						['y'] = -17639.5,
						['formation_template'] = '',
						['name'] = 'Land: 132/17NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['x'] = -397971,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Land',
					},
				},
			},
			['hidden'] = false,
			['units'] = {
				[1] = {
					['alt'] = 1663,
					['hardpoint_racks'] = true,
					['alt_type'] = 'BARO',
					['livery_id'] = 'aggressor `desert` scheme',
					['skill'] = 'Player',
					['speed'] = 161.875,
					['type'] = 'F-5E-3',
					['Radio'] = {
						[1] = {
							['channels'] = {
								[1] = 232.6,
								[2] = 327,
								[3] = 320.8,
							},
						},
					},
					['unitId'] = 100011,
					['psi'] = 0,
					['y'] = -17639.5,
					['x'] = -397971,
					['name'] = 'Pack 3 - 64 FWS - Strike 1-1',
					['payload'] = {
						['pylons'] = {
							[1] = {
								['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
							},
							[7] = {
								['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
							},
							[4] = {
								['CLSID'] = '{MER-5E_MK82x5}',
							},
						},
						['fuel'] = 2046,
						['flare'] = 15,
						['ammo_type'] = 1,
						['chaff'] = 30,
						['gun'] = 100,
					},
					['heading'] = 0,
					['callsign'] = {
						['name'] = 'Enfield81',
					},
					['onboard_num'] = '024',
				},
				[2] = {
					['alt'] = 1663,
					['heading'] = 0,
					['hardpoint_racks'] = true,
					['callsign'] = {
						['name'] = 'Enfield82',
					},
					['psi'] = 0,
					['livery_id'] = 'aggressor `desert` scheme',
					['onboard_num'] = '012',
					['skill'] = 'High',
					['y'] = -17539.5,
					['x'] = -397871,
					['name'] = 'Pack 3 - 64 FWS - Strike 1-2',
					['payload'] = {
						['pylons'] = {
							[1] = {
								['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
							},
							[7] = {
								['CLSID'] = '{9BFD8C90-F7AE-4e90-833B-BFD0CED0E536}',
							},
							[4] = {
								['CLSID'] = '{MER-5E_MK82x5}',
							},
						},
						['fuel'] = 2046,
						['flare'] = 15,
						['ammo_type'] = 1,
						['chaff'] = 30,
						['gun'] = 100,
					},
					['speed'] = 161.875,
					['alt_type'] = 'BARO',
					['unitId'] = 100012,
					['type'] = 'F-5E-3',
				},
			},
			['y'] = -17639.5,
			['radioSet'] = true,
			['name'] = 'Pack 3 - 64 FWS - Strike 1',
			['communication'] = true,
			['x'] = -397971,
			['start_time'] = 1,
			['task'] = 'CAS',
			['frequency'] = 232.6,
		},
		['flight'] = 1,
		['role'] = 'main',
		['unitname'] = 'Pack 3 - 64 FWS - Strike 1-1',
		['pack_n'] = 3,
		['waypoints'] = {
			[1] = {
				['speed_locked'] = true,
				['airdromeId'] = 4,
				['ETA'] = 0,
				['alt_type'] = 'RADIO',
				['type'] = 'TakeOffParking',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['briefing_name'] = 'Taxi',
				['x'] = -397971,
				['y'] = -17639.5,
				['formation_template'] = '',
				['name'] = 'Taxi',
				['ETA_locked'] = true,
				['speed'] = 215.83333333333,
				['alt'] = 0,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'From Parking Area',
			},
			[2] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Departure',
				['ETA'] = 620,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 0,
				['y'] = -17639.5,
				['formation_template'] = '',
				['name'] = 'Departure',
				['x'] = -397971,
				['speed'] = 0,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['enabled'] = true,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['number'] = 1,
								['params'] = {
									['action'] = {
										['id'] = 'Option',
										['params'] = {
											['value'] = 393217,
											['variantIndex'] = 1,
											['name'] = 5,
											['formationIndex'] = 6,
										},
									},
								},
							},
							[2] = {
								['number'] = 2,
								['auto'] = false,
								['id'] = 'ControlledTask',
								['enabled'] = true,
								['params'] = {
									['task'] = {
										['id'] = 'Orbit',
										['params'] = {
											['altitude'] = 1663,
											['pattern'] = 'Circle',
											['speed'] = 143.88888888889,
										},
									},
									['stopCondition'] = {
										['time'] = 620,
									},
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[3] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Join',
				['ETA'] = 806.54270270271,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4876.8,
				['y'] = -43396.239620847,
				['formation_template'] = '',
				['name'] = 'Join: 287/17NM',
				['x'] = -382209.49576773,
				['speed'] = 161.875,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['enabled'] = true,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['number'] = 1,
								['params'] = {
									['action'] = {
										['id'] = 'Option',
										['params'] = {
											['value'] = 458753,
											['variantIndex'] = 1,
											['name'] = 5,
											['formationIndex'] = 7,
										},
									},
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[4] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 877.34723187402,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4876.8,
				['y'] = -56431.280537626,
				['formation_template'] = '',
				['name'] = 'Nav: 287/9NM',
				['x'] = -374232.87079104,
				['speed'] = 215.83333333333,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[5] = {
				['speed_locked'] = true,
				['briefing_name'] = 'IP',
				['ETA'] = 891.46923959603,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4572,
				['y'] = -59031.127618567,
				['formation_template'] = '',
				['name'] = 'IP: 287/2NM',
				['x'] = -372641.92793986,
				['speed'] = 215.83333333333,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['number'] = 1,
								['auto'] = false,
								['id'] = 'AttackGroup',
								['enabled'] = true,
								['params'] = {
									['expend'] = 'All',
									['weaponType'] = 2032,
									['groupId'] = 60,
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[6] = {
				['speed_locked'] = false,
				['briefing_name'] = 'Target',
				['ETA'] = 992.94491527171,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4572,
				['y'] = -83050.285714287,
				['formation_template'] = '',
				['name'] = 'Target: 287/16NM',
				['x'] = -357943.71428572,
				['speed'] = 277.5,
				['ETA_locked'] = true,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[7] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Egress',
				['ETA'] = 1124.4205909474,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4572,
				['y'] = -64006.731103427,
				['formation_template'] = '',
				['name'] = 'Egress: 017/20NM',
				['x'] = -326823.59590495,
				['speed'] = 277.5,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[8] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Nav',
				['ETA'] = 1138.5425986694,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4876.8,
				['y'] = -62342.544266163,
				['formation_template'] = '',
				['name'] = 'Nav: 132/2NM',
				['x'] = -329377.17891137,
				['speed'] = 215.83333333333,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[9] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Split',
				['ETA'] = 1377.9780361952,
				['alt_type'] = 'BARO',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['type'] = 'Turning Point',
				['alt'] = 4876.8,
				['y'] = -34126.633940328,
				['formation_template'] = '',
				['name'] = 'Split: 132/28NM',
				['x'] = -372672.59953685,
				['speed'] = 215.83333333333,
				['ETA_locked'] = false,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
							[1] = {
								['enabled'] = true,
								['auto'] = false,
								['id'] = 'WrappedAction',
								['number'] = 1,
								['params'] = {
									['action'] = {
										['id'] = 'Option',
										['params'] = {
											['value'] = 393217,
											['variantIndex'] = 1,
											['name'] = 5,
											['formationIndex'] = 6,
										},
									},
								},
							},
						},
					},
				},
				['action'] = 'Turning Point',
			},
			[10] = {
				['speed_locked'] = true,
				['airdromeId'] = 4,
				['ETA'] = 1517.8850632222,
				['alt_type'] = 'BARO',
				['type'] = 'Land',
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['briefing_name'] = 'Land',
				['x'] = -397971,
				['y'] = -17639.5,
				['formation_template'] = '',
				['name'] = 'Land: 132/17NM',
				['ETA_locked'] = false,
				['speed'] = 215.83333333333,
				['alt'] = 4876.8,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['action'] = 'Landing',
			},
		},
		['tgt_wp'] = 6,
		['target'] = {
			['elements'] = {
				[1] = {
					['name'] = '102 Radar',
				},
				[2] = {
					['name'] = '102 Command Post',
				},
			},
			['groupId'] = 60,
			['class'] = 'vehicle',
			['firepower'] = {
				['min'] = 20,
				['max'] = 40,
			},
			['y'] = -83050.285714287,
			['x'] = -357943.71428572,
			['name'] = '102 EWR Site',
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 3,
			['task'] = 'Strike',
			['attributes'] = {
				[1] = 'soft',
				[2] = 'SR',
			},
		},
	},
	['title'] = 'Desert Tiger 76',
	['day'] = 1,
	['coop'] = 1,
	['variation'] = 14,
	['mission_duration'] = 10800,
	['mission'] = 1,
}
