oob_air = {
	['blue'] = {
		[6] = {
			['number'] = 4,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '171 ARW',
			['livery'] = 'Standard USAF',
			['base'] = 'Nellis AFB',
		},
		[2] = {
			['number'] = 30,
			['type'] = 'F-5E-3',
			['name'] = '65 FWS',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[8] = {
			['number'] = 2,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '41 TAS',
			['livery'] = 'US Air Force',
			['base'] = 'Laughlin',
		},
		[3] = {
			['number'] = 18,
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USAF Aggressors',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['SEAD'] = true,
				['Reconnaissance'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = '34 TFS',
			['livery'] = '',
			['base'] = 'Nellis AFB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
		},
		[1] = {
			['number'] = 18,
			['type'] = 'F-5E-3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['player'] = true,
			['name'] = '64 FWS',
			['livery'] = {
				[1] = 'aggressor `snake` scheme',
				[2] = 'aggressor `desert` scheme',
				[3] = 'US USAF Grape 31',
			},
			['base'] = 'Nellis AFB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
		},
		[4] = {
			['number'] = 30,
			['inactive'] = true,
			['name'] = '4 TFS',
			['type'] = 'F-4E',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[5] = {
			['number'] = 2,
			['type'] = 'E-3A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '963 AWCS',
			['livery'] = 'usaf standard',
			['base'] = 'Nellis AFB',
		},
		[7] = {
			['number'] = 1,
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '40 TAS',
			['livery'] = 'US Air Force',
			['base'] = 'Nellis AFB',
		},
	},
	['red'] = {
		[13] = {
			['number'] = 2,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '1.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Tonopah Airport',
		},
		[7] = {
			['number'] = 9,
			['type'] = 'MiG-21Bis',
			['name'] = 'III./JG-8',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[1] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./76.IAP',
			['livery'] = {
				[1] = 'VVS Metal',
				[2] = 'VVS Grey',
				[3] = 'VVS Camo',
			},
			['base'] = 'Tonopah AFB',
		},
		[2] = {
			['number'] = 24,
			['type'] = 'MiG-21Bis',
			['name'] = '2./76.IAP',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[4] = {
			['number'] = 6,
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = '787.IAP',
			['livery'] = 'af standard',
			['base'] = 'Tonopah AFB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
		},
		[8] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Poland',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./26.PLM',
			['livery'] = 'Poland - Metal',
			['base'] = 'Groom Lake AFB',
		},
		[11] = {
			['number'] = 6,
			['type'] = 'MiG-15bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Czech Republic',
			['tasks'] = {
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '2./17.SLP',
			['livery'] = 'Czechoslovakia_Air Force',
			['base'] = 'Lincoln',
		},
		[9] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['name'] = '2./26.PLM',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[5] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Germany',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = 'I./JG-8',
			['livery'] = 'Germany East',
			['base'] = 'Creech AFB',
		},
		[10] = {
			['number'] = 5,
			['type'] = 'MiG-15bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Czech Republic',
			['tasks'] = {
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 5,
			},
			['name'] = '1./17.SLP',
			['livery'] = 'Czechoslovakia_Air Force',
			['base'] = 'Pahute Airstrip',
		},
		[14] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '2.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Tonopah AFB',
		},
		[3] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['inactive'] = true,
			['name'] = '35.IAP',
			['livery'] = {
				[1] = 'af standard',
				[2] = 'af standard-1',
				[3] = 'af standard-2',
			},
			['base'] = 'Tonopah AFB',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
		},
		[6] = {
			['number'] = 3,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Germany',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Strike'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = 'II./JG-8',
			['livery'] = 'Germany East',
			['base'] = 'Beatty',
		},
		[12] = {
			['number'] = 6,
			['type'] = 'MiG-15bis',
			['name'] = '3./17.SLP',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[15] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '3.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Groom Lake AFB',
		},
	},
}
